server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ianzhengnan/spring-cloud-config-repo.git
          username:
          password:
encrypt:
  key: foo # 设置对称加密