DELETE FROM SYS_USER_ROLES;
DELETE FROM SYS_ROLE;
DELETE FROM SYS_USER;

INSERT INTO SYS_USER (id,username,password) values (1, 'ianzheng', 'ianzheng');
INSERT INTO SYS_USER (id,username,password) values (2, 'kaka', 'kaka');

INSERT INTO SYS_ROLE (id, name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO SYS_ROLE (id, name) VALUES (2, 'ROLE_USER');

INSERT INTO SYS_USER_ROLES(SYS_USER_ID, ROLES_ID) VALUES (1,1);
INSERT INTO SYS_USER_ROLES(SYS_USER_ID, ROLES_ID) VALUES (2,2);
